# **Numpy**

## Introduction

NumPy (Numerical Python) is a core Python library used for fast numerical and scientific computing. It provides powerful support for multi-dimensional arrays, along with a wide range of mathematical, statistical, and linear algebra operations.

NumPy is highly efficient because it stores data in a compact form and performs computations using optimized C code, making it much faster than regular Python lists. It is widely used in data science, machine learning, AI, engineering, and scientific research, and forms the foundation for libraries like Pandas, SciPy, Scikit-learn, and TensorFlow.


# **Why do we need Numpy arrays  rather than Python standard sequences?**

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.



# **Why is NumPy fast?**

**Vectorization** describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

* vectorized code is more concise and easier to read

* fewer lines of code generally means fewer bugs

* the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

* vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

**Broadcasting** is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous.


In [1]:
# Importing the Numpy

import numpy as np

In [2]:
# Array Fundamentals

array= np.array([2, 3, 4])
print(array)

[2 3 4]


In [3]:
# Getting the data type of the array
array= np.array([2, 3, 4])
print(array.dtype)

int64


In [4]:
array = np.array([1.2, 3.5, 5.1])
print(array.dtype)

float64


In [5]:
# Getting the shape of the array

row1 = [1,  2,  3,  4,  5]
row2 = [6,  7,  8,  9, 10]
row3 = [11, 12, 13, 14, 15]
row4 = [16, 17, 18, 19, 20]

array = np.array([ row1, row2, row3, row4 ])
print(array.shape)

# This shape give the row, column numbers.
# Example (row, column)

(4, 5)


In [6]:
# Accessing the data from the array using index
row1 = [1,  2,  3,  4,  5]
print(row1[2])


3


In [7]:
# Replacing the element in the array using index
row1 = [1,  2,  3,  4,  5]
row1[2] = 30
print(row1)

[1, 2, 30, 4, 5]


In [8]:
# Slicing the array
row1 = [1,  2,  3,  4,  5]
print(row1[1:3])
print(row1[1:])
print(row1[:3])

[2, 3]
[2, 3, 4, 5]
[1, 2, 3]


## **Array Attributes**

This section covers the attributes such as *ndim*, *shape*, *size* and *dtype*

* ***ndim***: Returns the number of dimensions (axes) of the NumPy array.

* ***shape***: Gives the size of the array in each dimension as a tuple.

* ***size***: Returns the total number of elements in the array.

* ***dtype***: Shows the data type of the elements stored in the array.


In [9]:
# Case 1
array = np.array(20)

print(f"Array----: {array}")
print(f"No. of Dimensions----: {array.ndim}")
print(f"Shape of the array----: {array.shape}")
print(f"Size of the array----: {array.size}")
print(f"Data type of the array----: {array.dtype}")
print(f"Length of Shape----: {len(array.shape)}")



Array----: 20
No. of Dimensions----: 0
Shape of the array----: ()
Size of the array----: 1
Data type of the array----: int64
Length of Shape----: 0


In [10]:
array = np.array([20, 100])

print(f"Array----: {array}")
print(f"No. of Dimensions----: {array.ndim}")
print(f"Shape of the array----: {array.shape}")
print(f"Size of the array----: {array.size}")
print(f"Data type of the array----: {array.dtype}")
print(f"Length of Shape----: {len(array.shape)}")

Array----: [ 20 100]
No. of Dimensions----: 1
Shape of the array----: (2,)
Size of the array----: 2
Data type of the array----: int64
Length of Shape----: 1


In [11]:
array = np.array([20, 100, 22])

print(f"Array----: {array}")
print(f"No. of Dimensions----: {array.ndim}")
print(f"Shape of the array----: {array.shape}")
print(f"Size of the array----: {array.size}")
print(f"Data type of the array----: {array.dtype}")
print(f"Length of Shape----: {len(array.shape)}")

Array----: [ 20 100  22]
No. of Dimensions----: 1
Shape of the array----: (3,)
Size of the array----: 3
Data type of the array----: int64
Length of Shape----: 1


In [12]:
array = np.array([[20, 100, 22], [26, 10, 232] ])

print(f"Array----: {array}")
print(f"No. of Dimensions----: {array.ndim}")
print(f"Shape of the array----: {array.shape}")
print(f"Size of the array----: {array.size}")
print(f"Data type of the array----: {array.dtype}")
print(f"Length of Shape----: {len(array.shape)}")

Array----: [[ 20 100  22]
 [ 26  10 232]]
No. of Dimensions----: 2
Shape of the array----: (2, 3)
Size of the array----: 6
Data type of the array----: int64
Length of Shape----: 2


In [13]:
array = np.array([[20, 100, 22], [26, 10, 232], [22, 34, 455] ])

print(f"Array----: {array}")
print(f"No. of Dimensions----: {array.ndim}")
print(f"Shape of the array----: {array.shape}")
print(f"Size of the array----: {array.size}")
print(f"Data type of the array----: {array.dtype}")
print(f"Length of Shape----: {len(array.shape)}")

Array----: [[ 20 100  22]
 [ 26  10 232]
 [ 22  34 455]]
No. of Dimensions----: 2
Shape of the array----: (3, 3)
Size of the array----: 9
Data type of the array----: int64
Length of Shape----: 2


In [14]:
array = np.array([
    [[20, 100, 22],
     [26, 10, 232],
     [22, 34, 455]],

    [[20, 100, 22],
     [26, 10, 232],
     [22, 34, 455]]
])

print(f"Array----: {array}")
print(f"No. of Dimensions----: {array.ndim}")
print(f"Shape of the array----: {array.shape}")
print(f"Size of the array----: {array.size}")
print(f"Data type of the array----: {array.dtype}")
print(f"Length of Shape----: {len(array.shape)}")

Array----: [[[ 20 100  22]
  [ 26  10 232]
  [ 22  34 455]]

 [[ 20 100  22]
  [ 26  10 232]
  [ 22  34 455]]]
No. of Dimensions----: 3
Shape of the array----: (2, 3, 3)
Size of the array----: 18
Data type of the array----: int64
Length of Shape----: 3


# **Creation of Common Basic Arrays**

In [15]:
# If we need to create an array that filled with zeros we can use this method:

zero_array = np.zeros(5)
print(zero_array)


[0. 0. 0. 0. 0.]


In [16]:
# If we need to create array with shape specified we can use this method

# Note: First elemt is the dimension and second element is the row,
# third will be the column
zero_array = np.zeros(([2,3,5]))
print(zero_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [17]:
# If we need to create an array that filled with ones we can use this method:

one_array = np.ones(5)
print(one_array)


[1. 1. 1. 1. 1.]


In [18]:
# With Multiple dimension:
one_array = np.ones(([2,3,5]))
print(one_array)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [19]:
# The function "empty" creates an array whose initial content is random
# and depends on the state of the memory.

# Note: The reason to use "random" over "zeros" is speed.

empty_array = np.empty(5)
print(empty_array)


[1. 1. 1. 1. 1.]


In [20]:
# For creating an array with range we can use the function "arange"

arange_array = np.arange(15)
print(arange_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
# Note: The first value is start value, second value is the stop value
# third value is the step value

arange_array = np.arange(5, 34, 3)
print(arange_array)

[ 5  8 11 14 17 20 23 26 29 32]


In [22]:
# If we want to create an array with values that are spaced linearly in a specified intervel
# we can use "linspace"

linspace_array = np.linspace(2,20, num=5)
print(linspace_array)

[ 2.   6.5 11.  15.5 20. ]


# **Sort and Concatenate**

In [23]:
# If we want to sort the array we can use the following function

sort_array = np.array([1, 2, 30, 4, 5])
print(np.sort(sort_array))

[ 1  2  4  5 30]


In [26]:
# Partition

partition_array = np.array([1, 2, 30, 48, 5, 45, 65, 87])
print(np.partition(partition_array, 4))

[ 1  2  5 30 45 48 65 87]


In [27]:
# Concatenation of 1 D array

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)


[1 2 3 4 5 6]


In [28]:
# Concatenation of 2 D array

# Note: Here we are using axis = 0 whcih means that concatenation happened in row wise

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
# Concatenation of 2 D array

# Note: Here we are using axis = 1 whcih means that concatenation happened in Column wise

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.concatenate((a, b), axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


# **Reshape Arrays**

It's reshaping the array without changing the data.


In [32]:
# Reshape of 1 D array

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [33]:
# Reshape of 2 D array

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


# **Arrange Arrays**


Creates an array with evenly spaced values within a given range.

**Syntax**

`np.arange(start, stop, step)`



In [34]:
# Arrange the data in 1 D array

arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [35]:
# Arrange the data in 2 D array

arr_2d = np.arange(10, 22).reshape(3, 4)
print(arr_2d)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# **Add New axis to Array**

Adding a new axis is mainly used to increase the dimension of an array (very common in ML, broadcasting, etc.).

In [36]:
# Add new axis as a row (1 × 4)

arr = np.array([1, 2, 3, 4])
print(arr.shape)

row_arr = arr[np.newaxis, :]
print(row_arr)
print(row_arr.shape)


(4,)
[[1 2 3 4]]
(1, 4)


In [37]:
# Add new axis as a column (4 × 1)

col_arr = arr[:, np.newaxis]
print(col_arr)
print(col_arr.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


# **Indexing and Slicing**


In [38]:
# Indexing in 1D array

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # First element
print(arr[-1])   # Last element

10
50


In [39]:
# Indexing in 2D array

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[1, 2])   # Row 1, Column 2

6


In [40]:
# Slicing in 1D array

print(arr[1:4])

[20 30 40]


In [41]:
# Slicing in 2D array

print(arr2d[0:2, 1:3])

[[2 3]
 [5 6]]


In [42]:
# Entire row or column

print(arr2d[1, :])   # Entire row
print(arr2d[:, 0])   # Entire column


[4 5 6]
[1 4 7]


In [43]:
# Conditioning

arr = np.array([10, 20, 30, 40, 50])

print(arr> 25)

[False False  True  True  True]


# **Horizontal, Vertical Stack and Horizontal Split**

Horizontal Stack `(hstack)`: Combines multiple arrays by joining them side by side along columns.

Vertical Stack `(vstack)`: Combines multiple arrays by placing them one below the other along rows.

Horizontal Split `(hsplit)`: Divides an array into multiple smaller arrays by splitting it column-wise.

In [45]:
# Horizontal Stack

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6, 7],
              [7, 8, 89]])

result = np.hstack((a, b))
print(result)

[[ 1  2  5  6  7]
 [ 3  4  7  8 89]]


In [47]:
# Vertical Stack

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

result = np.vstack((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
# Horizontal Split

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])

split_arr = np.hsplit(arr, 2)
print(split_arr)


[array([[10, 20],
       [50, 60]]), array([[30, 40],
       [70, 80]])]


# **View and Copy**

**View**: A view is a new array object that shares the same data as the original array, so changes in one will affect the other.

**Copy**: A copy is a new array object that does not share data with the original array, so changes in one do not affect the other.

In gerenral,

View is a ***shallow copy*** that shares the same underlying data buffer, whereas,

Copy is a ***deep copy*** with its own independent memory allocation.

In [52]:
# Original array
arr = np.array([10, 20, 30, 40])

print("Original array:", arr)

# View (shallow copy)
view_arr = arr.view()

print("View array    :", view_arr)

# Copy (deep copy)
copy_arr = arr.copy()

# Modify view
view_arr[0] = 999

print("Modified View array :", view_arr)
print("Copy array    :", copy_arr)

Original array: [10 20 30 40]
View array    : [10 20 30 40]
Modified View array : [999  20  30  40]
Copy array    : [10 20 30 40]


# **Mathematical Operations in Arrays**

In [54]:
# Creating two arrays

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

# addition
print(f"addition: {a + b}")

# Substraction
print(f"Substraction :{a - b}")

# Multiplication
print(f"Multiplication: {a * b}")

# Division
print(f"Division: {a / b}")


addition: [12 24 35 48]
Substraction :[ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


In [56]:
# Total sum of array elements

arr = np.array([10, 20, 30, 40])

print(np.sum(arr))

100


In [57]:
# Sum along rows

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(np.sum(arr2d, axis=1))

[ 6 15]


In [58]:
# Sum along columns

print(np.sum(arr2d, axis=0))

[5 7 9]


# **Min, Max, Standard Deviation, Mean, Product**

Min `(min)`: Returns the smallest value in the array.

Max `(max)`: Returns the largest value in the array.

Mean `(mean)`: Calculates the average value of the array elements.

Standard Deviation `(std)`: Measures how much the values vary from the mean.

Product `(prod)`: Returns the multiplication of all elements in the array.

In [59]:
# Creating an array

arr = np.array([2, 4, 6, 8, 10])

print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std: {np.std(arr)}")
print(f"Product: {np.prod(arr)}")


Min: 2
Max: 10
Mean: 6.0
Std: 2.8284271247461903
Product: 3840


In [64]:
# 2D Array (axis-wise)

arr2d = np.array([[109, 20, 43],
                  [4, 54, 34]])

print(f"Min: {np.min(arr2d, axis=0)}")
print(f"Max: {np.max(arr2d, axis=1)}")
print(f"Mean: {np.mean(arr2d)}")
print(f"Std: {np.std(arr2d)}")
print(f"Product: {np.prod(arr2d)}")

Min: [ 4 20 34]
Max: [109  54]
Mean: 44.0
Std: 33.17127271199182
Product: 688426560


# **Generating Random Numbers**

NumPy provides the `numpy.random `module to generate random numbers for simulations, data analysis, and machine learning.

In [65]:
# Creating random Array

# uniform distribution (0 to 1)
np.random.rand()

0.18482917084392858

In [66]:
# Random 1D array
np.random.rand(5)

array([0.50340457, 0.75242081, 0.31626621, 0.38276197, 0.9850818 ])

In [67]:
# Random 2D array
np.random.rand(2, 3)

array([[0.5559357 , 0.97333951, 0.48798028],
       [0.59381303, 0.21827298, 0.64898732]])

In [68]:
# Random integers

np.random.randint(1, 10, size=5)

array([8, 7, 3, 4, 3])

In [69]:
# Random numbers from normal distribution
np.random.randn(4)

array([-0.7889483 ,  1.41184525, -0.35057669,  0.05407288])

# **Transpose**

Transpose of an array flips its axes, i.e., converts rows to columns and columns to rows.

In [70]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


# **Reverse**

Reverse flips the elements of an array along a specific axis.

In [71]:
# 1 D array

arr1d = np.array([1, 2, 3, 4])
reversed_arr = arr1d[::-1]
print(reversed_arr)

[4 3 2 1]


In [72]:
# 2 D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Reverse rows
print(arr2d[::-1, :])

# Reverse columns
print(arr2d[:, ::-1])

[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [73]:
# Reverse the array using function called "flip"

arr1d = np.array([1, 2, 3, 4])
reversed_arr = np.flip(arr1d)
print(reversed_arr)

[4 3 2 1]


In [76]:
# 2 D array

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Flip all elements (both axes)
print(np.flip(arr2d))
print("\n")

# Flip along rows (axis=0)
print(np.flip(arr2d, axis=0))
print("\n")

# Flip along columns (axis=1)
print(np.flip(arr2d, axis=1))

[[6 5 4]
 [3 2 1]]


[[4 5 6]
 [1 2 3]]


[[3 2 1]
 [6 5 4]]


# **Flatten** **and  Ravel**

Flattening converts a multi-dimensional array into a 1D array.

`flatten()` always returns a copy (deep copy) → changes in flat_arr won’t affect the original array

`ravel()` → returns a view (shallow copy) when possible

In [78]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [79]:
flat_view = arr.ravel()
flat_view[0] = 999
print(arr)       # Original array is affected

print("\n")
print(flat_view)

[[999   2   3]
 [  4   5   6]]


[999   2   3   4   5   6]
